var code = new Map();

code.set("ACC", "Academic Computing Center");
code.set("ALD", "Alder Hall");
code.set("AND", "Anderson Hall");
code.set("ARC", "Architecture Hall");
code.set("ART", "Art Building");
code.set("ATG", "Atmospheric Science and Geophysics Building");
code.set("BAG", "Bagley Hall");
code.set("BLD", "Bloedel Hall");
code.set("BMM", "Burke Memorial Museum");
code.set("BNS", "Benson Hall");
code.set("CDH", "Condon Hall");
code.set("CHB", "Chemistry Building");
code.set("CHL", "Chemistry Library");
code.set("CLK", "Clark Hall");
code.set("CMA", "Ceramic and Metal Arts Facility");
code.set("CMU", "Communications Building");
code.set("CSE", "Computer Science and Engineering");
code.set("CSH", "Conibear Shellhouse");
code.set("DEM", "Dempsey Hall");
code.set("DEN", "Denny Hall");
code.set("DRC", "Douglas Research Conservatory");
code.set("EEB", "Electrical Engineering Building");
code.set("EGL", "Eagleson Hall");
code.set("FSH", "Fishery Sciences Building");
code.set("FTR", "Fisheries Teaching and Research Center");
code.set("GA1", "Guthrie Annex 1");
code.set("GLD", "Gould Hall");
code.set("GTH", "Guthrie Hall");
code.set("GUG", "Guggenheim Hall");
code.set("GWN", "Gowen Hall");
code.set("HCK", "Hitchcock Hall");
code.set("HHL", "Harris Hydraulics");
code.set("HPT", "Hughes Penthouse Theatre");
code.set("HSA", "Health Sciences A-wing");
code.set("HSB", "Health Sciences B-wing");
code.set("HSD", "Health Sciences D-wing");
code.set("HSE", "Health Sciences E-wing");
code.set("HSH", "Health Sciences H-wing");
code.set("HSI", "Health Sciences I-wing");
code.set("HSJ", "Health Sciences J-wing");
code.set("HSK", "Health Sciences K-wing");
code.set("HSR", "Health Sciences R-wing");
code.set("HST", "Health Sciences T-wing");
code.set("HUT", "Hutchinson Hall");
code.set("ICT", "Instructional Center/Theatre");
code.set("JHN", "Johnson Hall");
code.set("KIN", "Kincaid Hall");
code.set("KNE", "Kane Hall");
code.set("LAW", "William Gates Hall");
code.set("LEW", "Lewis Hall");
code.set("LOW", "Loew Hall");
code.set("MAH", "Maple Hall");
code.set("MAR", "Marine Studies Building");
code.set("MEB", "Mechanical Engineering Building");
code.set("MGH", "Mary Gates Hall");
code.set("MKZ", "Mackenzie Hall");
code.set("MLR", "Miller Hall");
code.set("MNY", "Meany Hall");
code.set("MOR", "More Hall");
code.set("MSB", "Marine Sciences Building");
code.set("MUE", "Mueller Hall");
code.set("MUS", "Music Building");
code.set("NPL", "North Physics Lab");
code.set("OBS", "Jacobsen Observatory");
code.set("OCE", "Oceanography Building");
code.set("OCN", "Ocean Sciences Building");
code.set("OTB", "Oceanography Teaching Building");
code.set("OUG", "Odegaard Undergraduate Library");
code.set("PAA", "Physics/Astronomy Auditorium");
code.set("PAB", "Physics/Astronomy Bar");
code.set("PAR", "Parrington Hall");
code.set("PAT", "Physics/Astronomy Tower");
code.set("PDL", "Padelford Hall");
code.set("RAI", "Raitt Hall");
code.set("SAV", "Savery Hall");
code.set("SIG", "Sieg Hall");
code.set("SMI", "Smith Hall");
code.set("SWS", "Social Work/Speech and Hearing Sciences Building");
code.set("THO", "Thomson Hall");
code.set("UMC", "University Medical Center CC Wing");
code.set("WFS", "Winkenwerder Forest Science Lab");
