var buildingCodesArr = [
["ACC", "Academic Computing Center"],
["ALD", "Alder Hall"],
["AND", "Anderson Hall"],
["ARC", "Architecture Hall"],
["ART", "Art Building"],
["ATG", "Atmospheric Science and Geophysics Building"],
["BAG", "Bagley Hall"],
["BLD", "Bloedel Hall"],
["BMM", "Burke Memorial Museum"],
["BNS", "Benson Hall"],
["CDH", "Condon Hall"],
["CHB", "Chemistry Building"],
["CHL", "Chemistry Library"],
["CLK", "Clark Hall"],
["CMA", "Ceramic and Metal Arts Facility"],
["CMU", "Communications Building"],
["CSE", "Computer Science and Engineering"],
["CSH", "Conibear Shellhouse"],
["DEM", "Dempsey Hall"],
["DEN", "Denny Hall"],
["DRC", "Douglas Research Conservatory"],
["EEB", "Electrical Engineering Building"],
["EGL", "Eagleson Hall"],
["FSH", "Fishery Sciences Building"],
["FTR", "Fisheries Teaching and Research Center"],
["GA1", "Guthrie Annex 1"],
["GLD", "Gould Hall"],
["GTH", "Guthrie Hall"],
["GUG", "Guggenheim Hall"],
["GWN", "Gowen Hall"],
["HCK", "Hitchcock Hall"],
["HHL", "Harris Hydraulics"],
["HPT", "Hughes Penthouse Theatre"],
["HSA", "Health Sciences A-wing"],
["HSB", "Health Sciences B-wing"],
["HSD", "Health Sciences D-wing"],
["HSE", "Health Sciences E-wing"],
["HSH", "Health Sciences H-wing"],
["HSI", "Health Sciences I-wing"],
["HSJ", "Health Sciences J-wing"],
["HSK", "Health Sciences K-wing"],
["HSR", "Health Sciences R-wing"],
["HST", "Health Sciences T-wing"],
["HUT", "Hutchinson Hall"],
["ICT", "Instructional Center/Theatre"],
["JHN", "Johnson Hall"],
["KIN", "Kincaid Hall"],
["KNE", "Kane Hall"],
["LAW", "William Gates Hall"],
["LEW", "Lewis Hall"],
["LOW", "Loew Hall"],
["MAH", "Maple Hall"],
["MAR", "Marine Studies Building"],
["MEB", "Mechanical Engineering Building"],
["MGH", "Mary Gates Hall"],
["MKZ", "Mackenzie Hall"],
["MLR", "Miller Hall"],
["MNY", "Meany Hall"],
["MOR", "More Hall"],
["MSB", "Marine Sciences Building"],
["MUE", "Mueller Hall"],
["MUS", "Music Building"],
["NPL", "North Physics Lab"],
["OBS", "Jacobsen Observatory"],
["OCE", "Oceanography Building"],
["OCN", "Ocean Sciences Building"],
["OTB", "Oceanography Teaching Building"],
["OUG", "Odegaard Undergraduate Library"],
["PAA", "Physics/Astronomy Auditorium"],
["PAB", "Physics/Astronomy Bar"],
["PAR", "Parrington Hall"],
["PAT", "Physics/Astronomy Tower"],
["PDL", "Padelford Hall"],
["RAI", "Raitt Hall"],
["SAV", "Savery Hall"],
["SIG", "Sieg Hall"],
["SMI", "Smith Hall"],
["SWS", "Social Work/Speech and Hearing Sciences Building"],
["THO", "Thomson Hall"],
["UMC", "University Medical Center CC Wing"],
["WFS", "Winkenwerder Forest Science Lab"]
]

var buildingCodes = new Map(buildingCodesArr);
